# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170103_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechat',
            name='bind',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechat',
            name='head_portrait',
            field=models.URLField(default='http://www.baidu.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wechat',
            name='name',
            field=models.CharField(default='bear', max_length=200),
            preserve_default=False,
        ),
    ]
