# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20170105_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
