# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_point_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='bearing',
            field=models.CharField(default=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='speed',
            field=models.CharField(default=60, max_length=200),
            preserve_default=False,
        ),
    ]
